pagopa/selfcare-dashboard-groups-microfrontend

src/pages/dashboardGroupDetail/components/GroupMenu.tsx, src/pages/dashboardGroupDetail/components/MembersGroup.tsx
…new partygroup lenghts after dissociate
=> SELC-972 Refresh lista referenti post dissociazione referente da Gruppo non istantaneo

src/pages/dashboardGroups/components/GroupsTableProduct/GroupsTableProduct.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupProductTableColumns.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupsProductTable.tsx
* QA-Demo-modified navigation bar and page with group title and fixed behavior of confirm button in form
* SELC-1307_fixed the display of the arrow in the Groups table
=> SELC-1307 set arrow visible

src/pages/dashboardGroupEdit/components/GroupForm.tsx
Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>
=> SELC-1377 change tooltip to helpertext (#76)

.devops/deploy-pipelines.yml
Co-authored-by: anttorre <antonio.torre@everis.com>
=> SELC-1392 enabling assistance in PROD (#79)

src/pages/dashboardGroupDetail/components/GroupDetail.tsx
Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>
=> removed refuse

src/pages/dashboardGroupEdit/components/GroupForm.tsx
=> correct error toast when we have an already existent group name

openApi/dashboard-api-docs.json, src/api/DashboardApiClient.ts, src/api/__mocks__/DashboardApiClient.ts, src/services/groupsService.ts
* SELC-1412 - fixed tab pagination in groups and updated opneApi
* SELC-1412 - fixed test
* SELC-1412 - updated with last openApi
Co-authored-by: fp <federico.piacitelli@everis.com>
=> Selc 1412 update open api

src/pages/dashboardGroupEdit/components/GroupForm.tsx, src/services/__mocks__/usersService.ts
=> using fixed width box on select users in groupform + ellipsis and overflow text

src/pages/dashboardGroups/GroupsPage.tsx
=> SELC-1452 fixed bug for group tabs

src/locale/it.ts, src/pages/dashboardGroupEdit/AddGroupPage.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx
SELC-1474 product field populated
=> SELC-1474 product field populated

src/pages/dashboardGroupEdit/components/GroupForm.tsx
=> SELC-1381 resolved doubled error toast when we try to create a group with already existent name

src/locale/it.ts, src/pages/dashboardGroupDetail/components/GroupMenu.tsx
=> SELC-1171 modified last popup remaining to do

src/locale/it.ts, src/pages/dashboardGroupDetail/components/GroupMenu.tsx
=> rename CTA of confirm in suspend and reactivate popup

src/pages/dashboardGroupDetail/GroupDetailPage.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx, src/services/groupsService.ts
=> SELC-1556 Post legal review changes in mixPanel Events

src/pages/dashboardGroupEdit/AddGroupPage.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx
* PNPG-195 Resolved not-responsive groupPage
* PNPG-195 Use of Stack component instead of grid component and some improvements to the structure of the code
=> PNPG-195 Resolved not-responsive groupPage + using Stack instead of Grid component and some improvement to structure of code

package.json
* Bump version to 1.1.0 [skip ci]
* Bump version to 1.1.1 [skip ci]
* Bump version to 1.2.0 [skip ci]
* Bump version to 1.3.0 [skip ci]
* Bump version to 1.4.0 [skip ci]
* Bump version to 1.5.0 [skip ci]
* Update CODEOWNERS
* SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character
* SELC-2552-added-new-characters-accepted (#216)
* updated with common last versione
---------
Co-authored-by: pagopa-github-bot <>
=> Merge back from main (#220)

package.json, yarn.lock
=> Updating of the mui-italia library version in order to obtain the new changes to the ProductAvatar component

package.json, src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/index.ts, src/locale/locale-utils.ts, src/locale/sl.ts, yarn.lock
Added localization languages: english, german, french, slovenian
=> SELC-2582 Added localization languages: english, german, french, slovenian

.devops/deploy-pipelines.yml, package.json, yarn.lock
update depedency coomon-frontend 
add env vars in deploy pipeline
=> SELC 3127 update depedency and add env vars

package.json, src/microcomponents/mock_dashboard/Layout.tsx, src/utils/env.ts, yarn.lock
SELC-3135 add button to docs in header 
Update common library
=> SELC-3135 add button to docs in header and update common

package.json, src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/sl.ts, yarn.lock
SELC-3242 updated translation json files
updated common library
Add new text to json object
=> SELC-3242 updated translation json files

package.json, src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/sl.ts, yarn.lock
* SELC-3242 updated translation json files
Updated common library
To keep the translation files and common library updated
=> SELC-3242 updated translation json files and common library

src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/it.ts, src/locale/sl.ts, src/pages/dashboardGroupEdit/components/GroupForm.tsx
Updated group translations
In order to cover the uncovered string
Local execution
=> [SELC-3242] feat: Updated group translations

package.json, yarn.lock
Update commons library to version 1.34.12
Change footer label for privacy policy
=> [SELC-1712] feat: update commons to v. 1.34.12

.env.development.local, openApi/dashboard-api-docs.json
update dashboard swagger with new paths with versioning
In order to remove versioning from env variable and add it in the path.
=> [SELC-4341] Feat: update swagger with versioning in path

.env.development.local, openApi/dashboard-api-docs.json
- [SELC-4341] feat: Updated openApi in order to choose versioning when an api is called
Release in production of the worked features
Tested in local and DEV environment from developer team and in UAT from business analyst team with behaviour tests that respect the estabilished AC's
[SELC-4341]: https://pagopa.atlassian.net/browse/SELC-4341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release prod

src/microcomponents/mock_dashboard/Layout.tsx
hide documentation button
The documentation of selfcare at the moment is only in italian so it should not be avaible to other languages
=> [SELC-4492] Feat: hide documentation button from header

package.json, yarn.lock
updated selfcare commons version
To read from url query params the lang
Tested in local environment setting the language on the query parameter, the portal language changes and the correct language is selected in the switch on the footer
=> [SELC-5005] Feat: Predisposition for reading the language from query paramete

package.json, yarn.lock
update mui library version
To get the new color styles for chip and tag components
=> [SELC-4552] Feat: update mui library version

src/pages/dashboardGroupDetail/GroupDetailPage.tsx, src/pages/dashboardGroupDetail/components/MembersGroup.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupProductTableColumns.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupsProductTable.tsx
removed not neccessary chip color style
=> [SELC-4552] removed personalized chip style

package.json, yarn.lock
Update the mui italia library to get the new drawer
=> [SELC-4585] Feat:update mui-italia library

src/pages/dashboardGroups/GroupsPage.tsx, yarn.lock
[[SELC-4619] Feat: Scrollable tabs for groups](https://github.com/pagopa/selfcare-dashboard-groups-microfrontend/commit/9b997fbe0283c71f6fbc68d928204d0b88121a35)
[Bump braces from 3.0.2 to 3.0.3](https://github.com/pagopa/selfcare-dashboard-groups-microfrontend/commit/2fbde15558c7d3f016f557e214b62f72860ba5df)
[Bump ws from 7.5.9 to 7.5.10](https://github.com/pagopa/selfcare-dashboard-groups-microfrontend/commit/61de038af2749e2bc8c6e65d698298a370467aa4)
Tested in dev enviroment
[SELC-4619]: https://pagopa.atlassian.net/browse/SELC-4619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release Uat

src/decorators/withGroupDetail.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx
added sort for users when creating groups.
added sort of users when modifying groups
To help find users in the list
Tested by aiming in dev.
=> [SELC-5278] feat: sorted users by name 

src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/sl.ts
[SELC-4494] feat: Removed unused localized text
Removed unused text
[SELC-4494]: https://pagopa.atlassian.net/browse/SELC-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4494] feat: Removed unused localized text

openApi/dashboard-api-docs.json, package.json, src/decorators/withGroupDetail.tsx, src/microcomponents/mock_dashboard/App.tsx, src/microcomponents/mock_dashboard/data/party.ts, src/model/Party.tsx, src/pages/dashboardGroupDetail/GroupDetailPage.tsx, src/pages/dashboardGroupEdit/CloneGroupPage.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx, src/pages/dashboardGroups/GroupsPage.tsx, src/redux/store.ts, yarn.lock
Adapt pnpg dashboard to hadnle authorizations with the actions
updated the swagger
update common library
In order to have a better more scalable handling of the user roles and actions.
Tested in dev
=> [SELC-5263] feat: handle in pnpg dashboard to userProductActions

package.json, src/pages/dashboardGroups/GroupsPage.tsx, yarn.lock
updated commons library
imported CustomAlert
To show a info banner for the limited visibility of users in dashboard this PR introduces a new CustomAlert component that leverages MUI’s Alert component to provide a reusable and flexible way to display messages with different severities, styles, and customizations.
Tested by running application locally
=> [SELC-5578] Feat: add info banner for limited view based on product role

openApi/dashboard-api-docs.json, package.json, src/locale/it.ts, src/pages/dashboardGroupDetail/components/GroupActions.tsx, yarn.lock
Added warning message in modal for IO when deleting group
Added warning message in modal for IO when suspending group
updated selfcare commons library
To warn the user that by deleting or suspening a groups its stoping some functionalities related to an API Key
Tested in local enviroment
=> [SELC-5650] Feat: add warning message when deleting or suspending

src/pages/dashboardGroupDetail/components/GroupActions.tsx
Hidden the warning message for IO when suspending or eliminating
For prod release
Tested locally
=> [SELC-5650] Hide app io message for release in Prod

openApi/dashboard-api-docs.json, package.json, src/locale/it.ts, src/pages/dashboardGroupDetail/components/GroupActions.tsx, yarn.lock
Updated selfcare library version 
To update the version of the library to the same as the other dashboard FE
Tested in dev
=> [SELC-5842] Feat: update selfcare commons for new action 

src/locale/fr.ts, src/pages/dashboardGroupDetail/components/MembersGroup.tsx, src/pages/dashboardGroups/GroupsPage.tsx
[PNPG-215] feat: Resolved non-localized text
To ensure that translation is triggered correctly when changing the portal language
Tested in local, the text is correctly translated in all portal supported languages
[PNPG-215]: https://pagopa.atlassian.net/browse/PNPG-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PNPG-215] feat: Resolved non-localized text

src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/sl.ts
[SELC-5988] feat: Uploaded new translation files
In order to have all the texts in the portal translated into the languages ​​provided. There may be some texts still not translated that will be collected and promptly reported to the agency.
Tested in local environment
[SELC-5988]: https://pagopa.atlassian.net/browse/SELC-5988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5988] feat: Uploaded new translation files

package.json, src/locale/de.ts, src/locale/en.ts, src/locale/fr.ts, src/locale/sl.ts, yarn.lock
[SELC-5988] feat: Uploaded new translation files + various dependency upgrades
In order to release in uat environment the new translations and the upgraded of the project dependency triggered by dependabot
Tested in dev environment reporting the untranslated texts on another ticket and that there have been no regressions
[SELC-5988]: https://pagopa.atlassian.net/browse/SELC-5988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5988] feat: Uploaded new translation files + various dependency upgrades

package.json, yarn.lock
remove axios
remove node-fetch
remove react-router-hash-link
remove react-use-scrollspy
Removed unused dependencies to streamline the project and reduce maintenance overhead
Tested by running application in local enviroment
=> SELC-5953 Feat: remove not used dependecies

src/pages/dashboardGroups/GroupsPage.tsx
Removed Custom Alert
The 45 days period has passed so it no longer nedded to show the alert banner
=> Chore: removed custom alert from groups as its no longer nedded

package.json, yarn.lock
=> Update uat branch

package.json
=> hotfix: duplicated dependency in package.json

package.json, yarn.lock
=> hotfix: align x-data-grid dependencies versions

package.json, yarn.lock
branch alignment following hotfixes
Keep the branches aligned
=> branch alignment following hotfixes

src/pages/dashboardGroupDetail/GroupDetailPage.tsx, src/pages/dashboardGroupDetail/components/MembersGroup.tsx, src/pages/dashboardGroupEdit/components/GroupForm.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupProductTableColumns.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupsProductTable.tsx, src/utils/helpers.tsx
Fixed the issue where the label in the Chip component would break into a new line, improving the layout and maintaining label consistency.
Centralized the logic for the Chip component into a helper file, making it easier to manage and maintain the component's behavior and styling.
The style of the chip was not the desired one.
Tested by running application in local enviroment.
=> [SELC-6229] Fix Chip Component Label Style and Centralize Component Logic

src/pages/dashboardGroupEdit/components/GroupForm.tsx
Add product id to mix panel event 
Minor code improvments
To track for which product the groups are being created
=> [SELC-6339] feat: Add product_id attribute to mix panel event

package.json, yarn.lock
=> [SELC-6417]  updated common version

package.json, yarn.lock
The frontend would take a long time (8+ min) to start in local and build during deploy.
=> regenerate yarn lock to fix slow build time

package.json, yarn.lock
=> fix: update common version for status 404

src/pages/dashboardGroups/GroupsPage.tsx
css style changes for tabs
To adapt the tabs component to figma.
=> SELC-6540 feat: adjust layout of groups page

src/locale/it.ts, src/pages/dashboardGroupDetail/components/GroupActions.tsx, src/pages/dashboardGroups/GroupsPage.tsx
Add new custom banner
removed some old translation lines
To inform the users of the new functionality that is being developed for prod-io and deployed on 31/03
=> [SELC-6449] feature: info banner for prod io groups new functionality

src/pages/dashboardGroups/GroupsPage.tsx
Updated doc link
Banner only visible for io and io premium
=> Updated documentation link

package.json, src/model/__tests__/PartyGroup.test.ts, src/model/__tests__/PartyUser.test.ts, src/pages/dashboardGroupDetail/components/GroupActions.tsx, src/pages/dashboardGroupEdit/components/__tests__/GroupForm.test.tsx, src/pages/dashboardGroups/__tests__/GroupsPage.test.tsx, src/services/__tests__/groupsService.test.ts, src/services/__tests__/usersService.test.ts, src/setupTests.ts, yarn.lock
warning api key message when deleting and suspending groups for product IO
add types jest
move global import jest dom into single tests file
With the new feature being developed by deleting and susping groups will have impact  on the groups API Key.
=> [SELC-6717] feat: show warning message when deleting of suspending io groups

package.json, yarn.lock
Removed axios
The api calls are handled with codegen. Its not necessary to have axios library.
=> [SELC-4788] Removed axios library

src/pages/dashboardGroupDetail/components/GroupMenu.tsx, src/pages/dashboardGroups/GroupsPage.tsx, src/pages/dashboardGroups/components/GroupsTableProduct/components/GroupProductTableColumns.tsx
Switched docs to the portal develope.pagopa
=> [SELC-6890] feat: Update link for IO groups documentation

.github/workflows/create_release_branch.yml, .github/workflows/deploy_cdn.yml
=> Updated ubuntu version LTS

src/pages/dashboardGroups/GroupsPage.tsx
Removed banner io 
The 45 days period has exipired and so the banner should be removed.
=> [SELC-6823] feat: removed banner IO

src/pages/dashboardGroupEdit/components/GroupForm.tsx
add invisible area-live section 
To notify screen readers when selecting or not selecting a group member
=> [SELC-6991] feat: notify screen readers the selected users

e2e/setup/hooks.ts, e2e/tests/features/add-and-remove-member.feature, e2e/tests/features/create-and-remove-group.feature, e2e/tests/features/duplicate-and-delete-group.feature, e2e/tests/features/update-group-status.feature, e2e/tests/features/update-users-status.feature, e2e/tests/step-definitions/common-steps.ts, e2e/tsconfig.json, e2e/utils/login.ts, e2e/yarn.lock
updated login function to accept institution
fixed an issue with cookies
regenrated yarn lock to remove duplicated deeps
=> Update cucumber tests

openApi/dashboard-api-docs.json, src/model/Party.tsx
=> [SELC-7153] feat: update openApi

src/pages/dashboardGroupEdit/components/GroupForm.tsx
Add area label for select component
Make options selectable by keyboard
To improve component accesability
=> [SELC-6993] feat: enhance member selection functionality for accesability in GroupForm component

openApi/dashboard-api-docs.json, src/api/DashboardApiClient.ts, src/api/__mocks__/DashboardApiClient.ts, src/services/groupsService.ts, tsconfig.json
Add getMyUserGroups api
update openApi
update tsconfig to handle jest types
=> SELC-7484 feat: add getMyUserGroups API method and update related services and mocks

package.json, src/model/__tests__/PartyGroup.test.ts, src/model/__tests__/PartyUser.test.ts, src/pages/dashboardGroupEdit/components/__tests__/GroupForm.test.tsx, src/pages/dashboardGroups/__tests__/GroupsPage.test.tsx, src/setupTests.ts, yarn.lock
=> Refactor code structure for improved readability and maintainability

package.json, yarn.lock
=> chore: update @pagopa/selfcare-common-frontend dependency to version 1.34.72
